interface ProcessEnv {
  NEXT_PUBLIC_DOMAIN_URL: string;
  
  NOTION_CONTACT_API_KEY: string;
  NOTION_PARTNER_API_KEY: string;
  NOTION_ACADEMY_API_KEY: string;
  NOTION_BLOG_API_KEY: string;

  NOTION_CONTACT_DATABASE_ID: string;
  NOTION_PARTNER_DATABASE_ID: string;
  NOTION_ACADEMY_DATABASE_ID: string;
  NOTION_BLOG_DATABASE_ID: string;

  INDEXNOW_KEY: string;
}
